dataset_folder: datasets/uCDCR
setting: single
type_of_pairs: random
ratio: 10
max_pairs_train: 50000000
train_scope: subtopic
train_dataset_names:
  - ECBplus
dev_dataset_names:
  - ECBplus
dev_scope: subtopic
dev_type_of_pairs: all
max_pairs_dev: none
test_scope: subtopic
test_dataset_names:
  - CEREC
  - CD2CR
  - ECBplus
  - ECBplusMETAm
  - FCC
  - GVC
  - HyperCoref
  - MEANTIME
  - NewsWCL50
  - NiDENT
  - NP4E
  - WECEng
language_model: roberta-large
batch_size: 256
learning_rate: 5e-5
training_iterations: 25
use_cuda: true
fine_tune: false
weight_decay: 0.01
hidden_size: 1024