batch_size: 32
learning_rate: 5e-4
negative_positive_ratio: -1
training_iterations: 10
use_cuda: true
fine_tune: false
weight_decay: 0.01
hidden_size: 150
dataset_name: wec

train_positive_file: resources/wec/Train_Event_gold_mentions_PosPairs.pickle
train_negative_file: resources/wec/Train_Event_gold_mentions_NegPairs.pickle
dev_positive_file: resources/wec/Dev_Event_gold_mentions_validated_PosPairs.pickle
dev_negative_file: resources/wec/Dev_Event_gold_mentions_validated_NegPairs.pickle

train_embeddings_file: resources/wec/Train_Event_gold_mentions_roberta_large.pickle
dev_embeddings_file: resources/wec/Dev_Event_gold_mentions_validated_roberta_large.pickle

model_name: wec_pairwise_model
