defaults:
  - data_config: preprocess_E1-1-1
  - _self_

batch_size: 32
learning_rate: 5e-5
negative_positive_ratio: -1
training_iterations: 10
use_cuda: true
fine_tune: false
weight_decay: 0.01
hidden_size: 150
