"""Usage:
    inference_clustering.py --tmf=<TestMentionsFile> --predictions=<TestPredictionsPickle> [--print=readable]
            [--alt=<AverageLinkThresh>]

Options:
    -h --help                               Show this screen.
    --predictions=<TestPredictionsPickle>   Path to matrix prediction file generated by cross_doc_coref
    --print=<PrintFormat>                   readable/conll - print in human readable format or in the conll format [default: conll]
    --alt=<AverageLinkThresh>               The link threshold for the clustering algorithm [default: 0.7]
"""
import json
import pickle
from datetime import datetime

import pandas as pd
import torch
import numpy as np
from pathlib import Path
from itertools import chain
from sklearn.cluster import AgglomerativeClustering
from typing import List
from tqdm import tqdm
import pathlib
import hydra
from hydra.core.config_store import ConfigStore


from cdcr_lexical_diversity_pairwise_scoring import logger
from cdcr_lexical_diversity_pairwise_scoring.utils.io_utils import write_coref_scorer_results, write_coref_scorer_results_simple
from cdcr_lexical_diversity_pairwise_scoring.utils.embed_utils import EmbedFromFile
from cdcr_lexical_diversity_pairwise_scoring.coref_system.pairwise_model_kenton import PairwiseModelKenton
from cdcr_lexical_diversity_pairwise_scoring.constants import MAX_ALLOWED_BATCH_SIZE, PROJECT_ROOT, CLUSTERING_THRESHOLD, CONFIG_NAME
from cdcr_lexical_diversity_pairwise_scoring.preprocess_gen_pairs import Config
from cdcr_lexical_diversity_pairwise_scoring.utils.io_utils import get_dataset_info_save_path, get_model_info_save_path, get_encoding_cache_file, get_predicted_cluster_path, get_conll_files_root_path
from cdcr_lexical_diversity_pairwise_scoring.dataobjs.dataset import uCDCRDataSet, EvalPairsType

torch.serialization.add_safe_globals([PairwiseModelKenton, torch.nn.modules.linear.Linear, torch.nn.modules.container.Sequential, torch.nn.modules.activation.ReLU, EmbedFromFile, pathlib.WindowsPath])

agl_clust = AgglomerativeClustering(
        n_clusters=None,
        metric="precomputed",
        linkage="average",
        distance_threshold=CLUSTERING_THRESHOLD,
    )


def get_pairwise_model(
    model_file_path: Path,
    embeddings_file_paths: list[Path],
    use_cuda: bool
):
    pairwise_model = torch.load(model_file_path, weights_only=True)
    pairwise_model.set_embed_utils(EmbedFromFile(embeddings_file_paths, use_cuda))

    if use_cuda:
        pairwise_model.cuda()

    pairwise_model.eval()
    return pairwise_model


def predict_and_cluster(
    test_dataset: uCDCRDataSet,
    model: PairwiseModelKenton,
    experiment_name: str,
):
    # cached_file = f"predictions_{experiment_name}.pickle"
    # cached_path = PROJECT_ROOT / "experiment_cache_results" / cached_file
    # if cached_path.exists():
    #     with open(cached_path, "rb") as file:
    #         predictions = pickle.load(file)
    # else:
    #     predictions = {}

    # self.positive_pairs_eval_format[dataset][topic_id][pairs_type.value]
    now_ = datetime.now()
    save_filename = f'{now_.strftime("%Y-%m-%d_%H-%M-%S")}_inference_time.csv'
    inf_time_path = PROJECT_ROOT / "evaluation_results" / "output_files"/ save_filename
    experiment_results_dict = {}

    inference_time_df = pd.DataFrame()

    conll_path = get_conll_files_root_path()

    for dataset, topic_dict in test_dataset.positive_pairs_eval_format.items():
        logger.info(f"Scoring dataset {dataset}")
        experiment_results_dict[dataset] = {}

        for topic_id, mention_config in tqdm(topic_dict.items(), desc=f"Scoring topics in {dataset}", total=len(topic_dict)):
            mention_topic_dict = {m.mention_id: m for m in test_dataset.topics.topics_dict[topic_id].mentions}
            experiment_results_dict[dataset][topic_id] = {}

            for pairs_type in list(mention_config.keys()):
                experiment_results_dict[dataset][topic_id][pairs_type] = []

                all_pairs = test_dataset.positive_pairs_eval_format[dataset][topic_id][pairs_type] + test_dataset.negative_pairs_eval_format[dataset][topic_id][pairs_type]
                # key = f"{dataset}_{topic_id}_{pairs_type}"
                # if key in predictions:
                #     all_scores = predictions[key]
                # else:
                start = datetime.now()
                all_scores = score_mention_pairs(model, all_pairs)
                # predictions[key] = all_scores

                # correctly reshape mentions now
                used_mention_ids = list(set(chain.from_iterable([[pair[0].mention_id, pair[1].mention_id] for pair in all_pairs])))
                sim_df = pd.DataFrame(np.zeros((len(used_mention_ids), len(used_mention_ids))), index=used_mention_ids, columns=used_mention_ids)
                for i, pair in enumerate(all_pairs):
                    sim_df.loc[pair[0].mention_id, pair[1].mention_id] = all_scores[i]
                    sim_df.loc[pair[1].mention_id, pair[0].mention_id] = all_scores[i]

                clustering = agl_clust.fit(sim_df.values)
                true_clusters = [mention_topic_dict[m_id].coref_chain for m_id in used_mention_ids]
                predicted_clusters = [str(v) for v in clustering.labels_]
                end = datetime.now()

                output_folder_true = conll_path / dataset / pairs_type / topic_id
                output_folder_true.mkdir(parents=True, exist_ok=True)
                write_coref_scorer_results_simple(true_clusters, used_mention_ids, pairs_type, output_folder_true, dataset, topic_id, predictions=False)
                write_coref_scorer_results_simple(predicted_clusters, used_mention_ids, pairs_type, output_folder_true, dataset, topic_id, predictions=True)
                inference_time_df = pd.concat([inference_time_df, pd.DataFrame({
                    "experiment": experiment_name,
                    "dataset": dataset,
                    "topic": topic_id,
                    "pair_type": pairs_type,
                    "mentions": len(used_mention_ids),
                    "inference_time": (end-start).total_seconds()
                }, index=[0])])

                for i, m_id in enumerate(used_mention_ids):
                    m = mention_topic_dict[m_id]
                    m_save = {k: v for k, v in dict(m.__dict__).items() if k in ["mention_id", "tokens_str", "coref_chain", "topic", "subtopic", "doc", "topic_id",  "subtopic_id", "doc_id", "dataset", "mention_context", "tokens_number_context"]}
                    m_save["predicted_coref_chain"] = f"{dataset}_{topic_id}_{predicted_clusters[i]}"
                    experiment_results_dict[dataset][topic_id][pairs_type].append(m_save)

            # with open(cached_path, "wb") as file:
            #     pickle.dump(predictions, file)
            # logger.info(f"Cached predictions of topic {topic_id}")
            inference_time_df.to_csv(inf_time_path)

    exp_dict_path = get_predicted_cluster_path()
    with exp_dict_path.open("w") as file:
        json.dump(experiment_results_dict, file)

    logger.info(f"The files for the CoNLL scorer are saved into: {conll_path}.")
    logger.info(f"The files with true and predicted predictions_json are saved into: {exp_dict_path}.")


def score_mention_pairs(model: PairwiseModelKenton, all_pairs: list) -> List[float]:
    """
    Run the mention scoring model in the prediction mode.
    """
    pairs_chunks = [all_pairs]
    if len(all_pairs) > MAX_ALLOWED_BATCH_SIZE:
        pairs_chunks = [
            all_pairs[i: i + MAX_ALLOWED_BATCH_SIZE] for i in range(0, len(all_pairs), MAX_ALLOWED_BATCH_SIZE)
        ]
    predictions = np.empty(0)
    with torch.no_grad():
        for chunk in pairs_chunks:
            chunk_predictions, _ = model.predict(chunk, bs=len(chunk))
            predictions = np.append(predictions, chunk_predictions.detach().cpu().numpy())
    predictions = 1 - predictions
    return predictions.tolist()


@hydra.main(version_base="1.3", config_path=str(PROJECT_ROOT / "config"), config_name=CONFIG_NAME)
def main(config: Config):
    model_config_path = get_model_info_save_path()
    with open(model_config_path, "r") as file:
        model_config = json.load(file)

    dataset_file_path = get_dataset_info_save_path()
    with open(dataset_file_path, "r") as file:
        dataset_config = json.load(file)

    with open(dataset_config["test"], "rb") as file:
        test_dataset = pickle.load(file)

    cached_embeddings_paths = [get_encoding_cache_file("test", dataset_name, config.language_model) for dataset_name in test_dataset.dataset_components]
    model = get_pairwise_model(
        model_file_path=model_config["model"],
        embeddings_file_paths=cached_embeddings_paths,
        use_cuda=config.use_cuda
    )

    logger.info(f"Running mention scoring with model: {type(model).__name__}")
    predict_and_cluster(test_dataset=test_dataset, model=model, experiment_name=CONFIG_NAME)


if __name__ == "__main__":
    main()
