"""Usage:
    inference_clustering.py --tmf=<TestMentionsFile> --predictions=<TestPredictionsPickle> [--print=readable]
            [--alt=<AverageLinkThresh>]

Options:
    -h --help                               Show this screen.
    --predictions=<TestPredictionsPickle>   Path to matrix prediction file generated by cross_doc_coref
    --print=<PrintFormat>                   readable/conll - print in human readable format or in the conll format [default: conll]
    --alt=<AverageLinkThresh>               The link threshold for the clustering algorithm [default: 0.7]
"""
import json
import pickle

import pandas as pd
import torch
import numpy as np
from pathlib import Path
from itertools import chain
from sklearn.cluster import AgglomerativeClustering
from hydra.core.config_store import ConfigStore
from typing import List
from tqdm import tqdm

from cdcr_lexical_diversity_pairwise_scoring import logger
from cdcr_lexical_diversity_pairwise_scoring.dataobjs.cluster import Clusters
from cdcr_lexical_diversity_pairwise_scoring.dataobjs.topics import Topics
from cdcr_lexical_diversity_pairwise_scoring.utils.clustering_utils import agglomerative_clustering
from cdcr_lexical_diversity_pairwise_scoring.utils.io_utils import write_coref_scorer_results, write_coref_scorer_results_simple
from cdcr_lexical_diversity_pairwise_scoring.utils.embed_utils import EmbedFromFile
from cdcr_lexical_diversity_pairwise_scoring.coref_system.pairwise_model_kenton import PairwiseModelKenton
from cdcr_lexical_diversity_pairwise_scoring.constants import MAX_ALLOWED_BATCH_SIZE, PROJECT_ROOT, CLUSTERING_THRESHOLD, CACHED_VECTOR_PATH, USE_CUDA
from cdcr_lexical_diversity_pairwise_scoring.preprocess_gen_pairs import Config
from cdcr_lexical_diversity_pairwise_scoring.utils.io_utils import get_model_name, get_dataset_config_name, get_model_config_name, get_experiment_name
from cdcr_lexical_diversity_pairwise_scoring.dataobjs.dataset import uCDCRDataSet, EvalPairsType

CONFIG_NAME = "preprocess_test"
cs = ConfigStore.instance()
cs.store(name=CONFIG_NAME, node=Config)

agl_clust = AgglomerativeClustering(
        n_clusters=None,
        metric="precomputed",
        linkage="average",
        distance_threshold=CLUSTERING_THRESHOLD,
    )


def get_pairwise_model(
    model_file_path: Path,
    embeddings_file_path: Path,
    use_cuda: bool = USE_CUDA,
):
    pairwise_model = torch.load(model_file_path)
    pairwise_model.set_embed_utils(EmbedFromFile(embeddings_file_path))

    if use_cuda:
        pairwise_model.cuda()

    pairwise_model.eval()
    return pairwise_model


def predict_and_cluster(
    test_dataset: uCDCRDataSet,
    model: PairwiseModelKenton,
    experiment_name: str
):
    # self.positive_pairs_eval_format[dataset][topic_id][pairs_type.value]
    experiment_results_dict = {}

    for dataset, topic_dict in test_dataset.positive_pairs_eval_format.items():
        logger.info(f"Scoring dataset {dataset}")
        experiment_results_dict[dataset] = {}

        for topic_id, mention_config in tqdm(topic_dict.items(), desc=f"Scoring topics in {dataset}", total=len(topic_dict)):
            mention_topic_dict = {m.mention_id: m for m in test_dataset.topics[topic_id].mentions}
            experiment_results_dict[dataset][topic_id] = {}

            for pairs_type in list(mention_config.keys()):
                experiment_results_dict[dataset][topic_id][pairs_type] = []

                all_pairs = test_dataset.positive_pairs_eval_format[pairs_type] + test_dataset.negative_pairs_eval_format[pairs_type]
                all_scores = score_mention_pairs(model, all_pairs)

                # correctly reshape mentions now
                used_mention_ids = list(set(chain.from_iterable([[pair[0].mention_id, pair[0].mention_id] for pair in all_pairs])))
                sim_df = pd.DataFrame(np.zeros((len(used_mention_ids), len(used_mention_ids))), index=used_mention_ids, columns=used_mention_ids)
                for i, pair in enumerate(all_pairs):
                    sim_df.loc[pair[0].mention_id, pair[1].mention_id] = all_scores[i]
                    sim_df.loc[pair[1].mention_id, pair[2].mention_id] = all_scores[i]

                clustering = agl_clust.fit(sim_df.values)
                true_clusters = [mention_topic_dict[m_id].coref_chain for m_id in used_mention_ids]
                predicted_clusters = clustering.labels_

                output_folder_true = PROJECT_ROOT / "evaluation_results" / "input_files" / experiment_name / dataset / pairs_type / topic_id
                output_folder_true.mkdir(parents=True, exist_ok=True)
                write_coref_scorer_results_simple(true_clusters, output_folder_true, topic_id, predictions=False)
                write_coref_scorer_results_simple(predicted_clusters, output_folder_true, topic_id, predictions=True)

                for i, m_id in enumerate(used_mention_ids):
                    m = mention_topic_dict[m_id]
                    m_save = {k: v for k, v in dict(m.__dict__) if k in ["mention_id", "tokens_str", "coref_chain", "topic", "subtopic", "doc", "topic_id",  "subtopic_id", "doc_id", "dataset", "mention_context", "tokens_number_context"]}
                    m_save["predicted_coref_chain"] = f"{dataset}_{topic_id}_{predicted_clusters[i]}"
                    experiment_results_dict[dataset][topic_id][pairs_type].append(m_save)

    file_name = f"results_{experiment_name}.json"
    exp_dict_path = PROJECT_ROOT / "evaluation_results" / "clusters" / file_name
    with exp_dict_path.open("w") as file:
        json.dump(experiment_results_dict, file)

    logger.info(f"The files for the CoNLL scorer are saved into: {PROJECT_ROOT / 'evaluation_results' / 'input_files' / experiment_name}.")
    logger.info(f"The files with true and predicted clusters are saved into: {exp_dict_path}.")


def score_mention_pairs(model: PairwiseModelKenton, all_pairs: list) -> List[float]:
    """
    Run the mention scoring model in the prediction mode.
    """
    pairs_chunks = [all_pairs]
    if len(all_pairs) > MAX_ALLOWED_BATCH_SIZE:
        pairs_chunks = [
            all_pairs[i: i + MAX_ALLOWED_BATCH_SIZE] for i in range(0, len(all_pairs), MAX_ALLOWED_BATCH_SIZE)
        ]
    predictions = np.empty(0)
    with torch.no_grad():
        for chunk in pairs_chunks:
            chunk_predictions, _ = model.predict(chunk, bs=len(chunk))
            predictions = np.append(predictions, chunk_predictions.detach().cpu().numpy())
    predictions = 1 - predictions
    return predictions.tolist()


def main(config_name: str):
    model_config_name = get_model_config_name(config_name)
    model_config_path = PROJECT_ROOT / "config" / model_config_name
    with open(model_config_path, "r") as file:
        model_config = json.load(file)

    file_name = get_dataset_config_name(config_name)
    dataset_file_path = PROJECT_ROOT / "config" / file_name
    with open(dataset_file_path, "r") as file:
        dataset_config = json.load(file)

    model = get_pairwise_model(
        model_file_path=model_config["model"],
        embeddings_file_path=CACHED_VECTOR_PATH,
    )

    with open(dataset_config["test"], "rb") as file:
        test_dataset = pickle.load(file)

    logger.info(f"Running mention scoring with model: {model.__name__}")
    exp_name = get_experiment_name(config_name)
    predict_and_cluster(test_dataset=test_dataset, model=model, experiment_name=exp_name)


if __name__ == "__main__":
    # arguments = docopt(__doc__, argv=None, help=True, version=None, options_first=False)
    # TODO Sergei read experiment config file
    config_file = CONFIG_NAME
    main(config_file)
