dataset_folder: datasets/uCDCR
setting: single
type_of_pairs: tfidf
ratio: 1
max_pairs_train: 50000
train_scope: subtopic
train_dataset_names:
  - GVC
dev_scope: subtopic
dev_type_of_pairs: all
max_pairs_dev: 8000
test_scope: subtopic
test_dataset_names:
  - GVC
